apiVersion: v1
kind: Pod
metadata:
  name: "api-test-pod"
spec:
  containers:
  - name: python-container
    image: gabrielphilot/btc-edc-m3-spark:3.1.1
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    command: ["bash", "-c", "python3 -u /app/api_to_bronze.py"]