apiVersion: v1
kind: Pod
metadata:
  name: "brewapi-ingestion-minio"
spec:
  containers:
  - name: python-container
    image: gabrielphilot/brewapi-ingestion-minio:0.1
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    command: ["bash", "-c", "python3 -u /app/api_to_bronze.py"]