# docker image [gcp]
FROM apache/spark-py:v3.3.2
# Switch to user root so we can add additional jars and configuration files.
USER root
# create directory for apps
RUN mkdir -p /app

# Spark jars
COPY jars/*.jar $SPARK_HOME/jars/
RUN chmod 644 $SPARK_HOME/jars/*.jar

COPY resources/ /app/resources/
COPY config/ /app/config/

# set work directory
WORKDIR /app

USER ${spark_uid}

COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

COPY bronze_to_silver.py silver_to_gold.py /app/