apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  namespace: cicd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "latest"
    chart: "prometheus"
    helm:
      values: |-
        alertmanager:
          enabled: true
        server:
          service:
            type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
