apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jupyter
  project: default
  source:
    repoURL: 'https://jupyterhub.github.io/helm-chart/'
    targetRevision: 3.0.0
    chart: jupyterhub
    helm:
      values: |
        hub:
          config:
            Authenticator:
              admin_users:
                - admin
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "500m"
          extraEnv:
            MINIO_ENDPOINT: "http://minio-service.deepstorage.svc.cluster.local:9000"
            MINIO_ACCESS_KEY:
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root-user
            MINIO_SECRET_KEY:
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root-password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true