apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jupyter
  project: default
  source:
    repoURL: 'https://jupyterhub.github.io/helm-chart/'
    targetRevision: 3.0.0
    chart: jupyterhub
    helm:
      values: |
        hub:
          config:
            Authenticator:
              admin_users:
                - admin
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "500m"
        singleuser:
          profileList:
            - display_name: "Python Data Science"
              description: "Ambiente com pacotes para análise de dados"
              default: true
          image:
            name: jupyter/datascience-notebook
            tag: latest
          extraPackages:
            - duckdb
            - pandas
            - requests
            - pyyaml
            - json5
          storage:
            type: none
          extraEnv:
            MINIO_ENDPOINT: "http://minio-service.deepstorage.svc.cluster.local:9000"
            MINIO_ACCESS_KEY:
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root-user
            MINIO_SECRET_KEY:
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root-password
        service:
          type: ClusterIP  # Mudando para ClusterIP pois vamos acessar via tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true