apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-spark-operator-processor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: meuspark-spark-operator-controller
    namespace: processor
  - kind: ServiceAccount
    name: default
    namespace: processor
