apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: deepstorage
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "deepstorage,processing"
type: Opaque
data:
  root-user: "YnJld2VyeXVzZXI="
  root-password: "bWluaW9zZWNyZXQ="